import type { ReviewsCopy } from './types';

export const arReviewsCopy: ReviewsCopy = {
  actionConflict: 'تغيّرت هذه المراجعة في الخادم. أُعيدت مزامنة القائمة والتفاصيل؛ راجع الحالة الجديدة قبل المحاولة.',
  actionError: 'تعذر إكمال الإجراء. تحقّق من اتصال الخادم وأعد المحاولة.',
  actionUnavailable: 'لا يمكن اتخاذ قرار لأن المراجعة معيّنة إلى مراجع آخر أو انتهت بالفعل.',
  all: 'الكل', applyFilters: 'تطبيق الفلاتر', answer: 'الإجابة المسجلة', answerLanguage: 'لغة الإجابة',
  approveAsIs: 'اعتماد كما هي', approveEdited: 'تحرير واعتماد', assignedReviewer: 'المراجع المعيّن',
  cancel: 'إلغاء', channel: 'القناة',
  chooseReviewBody: 'اختر عنصرًا من الطابور لعرض السؤال والإجابة والأدلة وسجل المراجعة.',
  chooseReviewTitle: 'اختر مراجعة', claim: 'استلام المراجعة', clearFilters: 'مسح الفلاتر',
  closeDetails: 'إغلاق التفاصيل', confirmDecision: 'تأكيد القرار النهائي', correctedAnswer: 'الإجابة المصححة',
  createdAt: 'أُنشئت', decidedAt: 'وقت القرار', decision: 'القرار',
  decisionDescriptions: {
    approve_as_is: 'سيُعتمد نص الإجابة المسجلة دون تغيير، ولا يمكن التراجع عن القرار من هذه الواجهة.',
    approve_edited: 'ستصبح الصياغة المصححة هي الإجابة المعتمدة، ولا يمكن التراجع عن القرار من هذه الواجهة.',
    needs_changes: 'سيُطلب تعديل المحتوى الأساسي. يلزم توضيح السبب في الملاحظات الداخلية.',
    reject: 'ستُرفض الإجابة المسجلة، ولا يمكن التراجع عن القرار من هذه الواجهة.',
  },
  decisionTitles: {
    approve_as_is: 'تأكيد الاعتماد كما هو', approve_edited: 'تأكيد التحرير والاعتماد',
    needs_changes: 'تأكيد طلب تعديل المحتوى', reject: 'تأكيد رفض الإجابة',
  },
  details: 'تفاصيل المراجعة', emptyBody: 'لا توجد مراجعات تطابق الفلاتر الحالية.', emptyTitle: 'الطابور فارغ',
  eventDecision: 'مرجع القرار', eventFrom: 'من', eventHistory: 'سجل الأحداث', eventReviewer: 'المراجع', eventTo: 'إلى',
  eventTypes: { claimed: 'تم الاستلام', created: 'أُنشئت المراجعة', decision_saved: 'حُفظ القرار', released: 'أُعيدت إلى الطابور', status_changed: 'تغيّرت الحالة' },
  evidence: 'مراجع الأدلة', filterAnswerLanguage: 'اللغة', filterChannel: 'القناة',
  filterReviewer: 'المراجع المعيّن', filterStatus: 'الحالة', filters: 'فلاتر الطابور', grounded: 'مستندة إلى دليل',
  internalNotes: 'ملاحظات داخلية', languagePlaceholder: 'مثل ar أو en-US',
  loadDetailsError: 'تعذر تحميل تفاصيل المراجعة.', loadListError: 'تعذر تحميل طابور المراجعات من الخادم.',
  loadingDetails: 'جارٍ تحميل التفاصيل…', loadingList: 'جارٍ تحميل الطابور…', metadata: 'بيانات الإجابة والمراجعة',
  model: 'النموذج', needsChanges: 'طلب تعديل المحتوى', no: 'لا', noDecision: 'لم يُحفظ قرار نهائي بعد.',
  noEvents: 'لا توجد أحداث مسجلة.', noEvidence: 'لا توجد مراجع أدلة محفوظة لهذه الإجابة.', notAvailable: 'غير متاح',
  notesOptional: 'اختيارية لهذا القرار', notesRequired: 'مطلوبة لشرح التعديل المطلوب',
  outcomes: { approved: 'معتمدة', needs_changes: 'تحتاج تعديل المحتوى', rejected: 'مرفوضة' },
  previousPage: 'الصفحة السابقة', nextPage: 'الصفحة التالية', provider: 'المزوّد', question: 'السؤال',
  queueLabel: 'طابور مراجعة المعلمين', refresh: 'تحديث', reject: 'رفض', release: 'إعادة إلى الطابور',
  reviewerFilterPlaceholder: 'معرّف المراجع بالضبط', reviewerId: 'معرّف المراجع المؤقت',
  reviewerPlaceholder: 'مثال: teacher-fatima', reviewerSession: 'جلسة المراجع المحلية',
  reviewerWarning: 'هذا المعرّف يدخله المشغّل ويُحفظ محليًا في هذا المتصفح. ليس تسجيل دخول ولا يثبت الهوية أو الصلاحية.',
  retry: 'إعادة المحاولة', status: 'حالة المراجعة',
  statuses: { approved: 'معتمدة', in_review: 'قيد المراجعة', needs_changes: 'تحتاج تعديلًا', pending: 'بانتظار المراجعة', rejected: 'مرفوضة' },
  submitDecision: 'تأكيد وحفظ القرار', submitting: 'جارٍ الحفظ…',
  successClaim: 'تم استلام المراجعة ومزامنة الطابور.', successDecision: 'تم حفظ القرار النهائي ومزامنة البيانات.',
  successRelease: 'أُعيدت المراجعة إلى الطابور وتمت المزامنة.',
  sufficiencies: { insufficient: 'غير كافٍ', sufficient: 'كافٍ', unknown: 'غير معروف' }, sufficiency: 'كفاية الدليل',
  unassigned: 'غير معيّنة', updatedAt: 'آخر تحديث',
  validation: {
    correction_required: 'أدخل صياغة مصححة قبل الاعتماد.', correction_too_long: 'تتجاوز الإجابة المصححة الحد المسموح.',
    notes_required: 'اشرح بوضوح ما الذي يجب تعديله في المحتوى.', notes_too_long: 'تتجاوز الملاحظات الحد المسموح.',
    request_too_large: 'حجم نص القرار أكبر من الحد الذي يقبله الخادم.', reviewer_required: 'أدخل معرّف المراجع أولًا.',
    reviewer_too_long: 'معرّف المراجع أطول من الحد المسموح.',
  },
  viewDetails: (question) => `عرض تفاصيل المراجعة: ${question}`,
  rangeLabel: (start, end, total) => `${start.toLocaleString('ar-EG')}–${end.toLocaleString('ar-EG')} من ${total.toLocaleString('ar-EG')}`,
  reviewCount: (count) => `${count.toLocaleString('ar-EG')} مراجعة`, yes: 'نعم', unknown: 'غير معروف',
};
