import type { ReviewsCopy } from './types';

export const enReviewsCopy: ReviewsCopy = {
  actionConflict: 'This review changed on the server. The queue and details were resynced; check the new state before trying again.',
  actionError: 'The action could not be completed. Check the local server and try again.',
  actionUnavailable: 'A decision is unavailable because another reviewer owns this item or it is already final.',
  all: 'All', applyFilters: 'Apply filters', answer: 'Recorded answer', answerLanguage: 'Answer language', approveAsIs: 'Approve as-is',
  approveEdited: 'Edit and approve', assignedReviewer: 'Assigned reviewer', cancel: 'Cancel', channel: 'Channel',
  chooseReviewBody: 'Select an item from the queue to inspect the question, answer, evidence, and audit history.',
  chooseReviewTitle: 'Select a review', claim: 'Claim review', clearFilters: 'Clear filters', closeDetails: 'Close details',
  confirmDecision: 'Confirm final decision', correctedAnswer: 'Corrected answer', createdAt: 'Created', decidedAt: 'Decided', decision: 'Decision',
  decisionDescriptions: {
    approve_as_is: 'The recorded answer will be approved unchanged. This decision cannot be reversed in this workspace.',
    approve_edited: 'The corrected wording will become the approved answer. This decision cannot be reversed in this workspace.',
    needs_changes: 'A change to the underlying content will be requested. Clear internal notes are required.',
    reject: 'The recorded answer will be rejected. This decision cannot be reversed in this workspace.',
  },
  decisionTitles: { approve_as_is: 'Confirm as-is approval', approve_edited: 'Confirm edited approval', needs_changes: 'Confirm content change request', reject: 'Confirm rejection' },
  details: 'Review details', emptyBody: 'No reviews match the current filters.', emptyTitle: 'The queue is empty',
  eventDecision: 'Decision reference', eventFrom: 'From', eventHistory: 'Audit history', eventReviewer: 'Reviewer', eventTo: 'To',
  eventTypes: { claimed: 'Claimed', created: 'Review created', decision_saved: 'Decision saved', released: 'Released to queue', status_changed: 'Status changed' },
  evidence: 'Evidence references', filterAnswerLanguage: 'Language', filterChannel: 'Channel', filterReviewer: 'Assigned reviewer',
  filterStatus: 'Status', filters: 'Queue filters', grounded: 'Grounded', internalNotes: 'Internal notes',
  languagePlaceholder: 'e.g. ar or en-US', loadDetailsError: 'The review details could not be loaded.',
  loadListError: 'The review queue could not be loaded from the server.', loadingDetails: 'Loading review details…',
  loadingList: 'Loading review queue…', metadata: 'Answer and review metadata', model: 'Model', needsChanges: 'Request content change',
  no: 'No', noDecision: 'No final decision has been saved.', noEvents: 'No events are recorded.',
  noEvidence: 'No evidence references were stored for this answer.', notAvailable: 'Not available', notesOptional: 'Optional for this decision',
  notesRequired: 'Required to explain the requested change', outcomes: { approved: 'Approved', needs_changes: 'Content changes needed', rejected: 'Rejected' },
  previousPage: 'Previous page', nextPage: 'Next page', provider: 'Provider', question: 'Question', queueLabel: 'Teacher review queue',
  refresh: 'Refresh', reject: 'Reject', release: 'Release to queue', reviewerFilterPlaceholder: 'Exact reviewer ID',
  retry: 'Try again', status: 'Review status',
  statuses: { approved: 'Approved', in_review: 'In review', needs_changes: 'Needs changes', pending: 'Pending', rejected: 'Rejected' },
  submitDecision: 'Confirm and save decision', submitting: 'Saving…', successClaim: 'Review claimed and queue resynced.',
  successDecision: 'Final decision saved and data resynced.', successRelease: 'Review released and queue resynced.',
  sufficiencies: { insufficient: 'Insufficient', sufficient: 'Sufficient', unknown: 'Unknown' }, sufficiency: 'Evidence sufficiency',
  unassigned: 'Unassigned', updatedAt: 'Last updated',
  validation: {
    correction_required: 'Enter corrected wording before approval.', correction_too_long: 'The corrected answer exceeds the allowed length.',
    notes_required: 'Clearly explain what needs to change in the content.', notes_too_long: 'The internal notes exceed the allowed length.',
    request_too_large: 'The decision text is larger than the server request limit.',
  },
  viewDetails: (question) => `View review details: ${question}`,
  rangeLabel: (start, end, total) => `${start}–${end} of ${total}`,
  reviewCount: (count) => `${count} ${count === 1 ? 'review' : 'reviews'}`, yes: 'Yes', unknown: 'Unknown',
};
