import type { ReviewsCopy } from './types';

export const swReviewsCopy: ReviewsCopy = {
  actionConflict: 'Mapitio haya yamebadilika kwenye seva. Foleni na maelezo yamesawazishwa; kagua hali mpya kabla ya kujaribu tena.',
  actionError: 'Kitendo hakikuweza kukamilika. Kagua seva ya ndani na ujaribu tena.',
  actionUnavailable: 'Uamuzi haupatikani kwa sababu mkaguzi mwingine amepangiwa au mapitio yamekamilika.',
  all: 'Zote', applyFilters: 'Tumia vichujio', answer: 'Jibu lililohifadhiwa', answerLanguage: 'Lugha ya jibu', approveAsIs: 'Idhinisha bila kubadili',
  approveEdited: 'Hariri na uidhinishe', assignedReviewer: 'Mkaguzi aliyepangiwa', cancel: 'Ghairi', channel: 'Kituo',
  chooseReviewBody: 'Chagua kipengee kwenye foleni ili kuona swali, jibu, ushahidi, na historia.', chooseReviewTitle: 'Chagua mapitio',
  claim: 'Chukua mapitio', clearFilters: 'Futa vichujio', closeDetails: 'Funga maelezo', confirmDecision: 'Thibitisha uamuzi wa mwisho',
  correctedAnswer: 'Jibu lililosahihishwa', createdAt: 'Yaliundwa', decidedAt: 'Uamuzi ulifanywa', decision: 'Uamuzi',
  decisionDescriptions: {
    approve_as_is: 'Jibu lililohifadhiwa litaidhinishwa bila kubadilishwa. Uamuzi huu hauwezi kubatilishwa hapa.',
    approve_edited: 'Maneno yaliyosahihishwa yatakuwa jibu lililoidhinishwa. Uamuzi huu hauwezi kubatilishwa hapa.',
    needs_changes: 'Mabadiliko ya maudhui ya msingi yataombwa. Maelezo ya ndani yanahitajika.',
    reject: 'Jibu lililohifadhiwa litakataliwa. Uamuzi huu hauwezi kubatilishwa hapa.',
  },
  decisionTitles: { approve_as_is: 'Thibitisha idhini', approve_edited: 'Thibitisha uhariri na idhini', needs_changes: 'Thibitisha ombi la kubadili maudhui', reject: 'Thibitisha kukataa' },
  details: 'Maelezo ya mapitio', emptyBody: 'Hakuna mapitio yanayolingana na vichujio.', emptyTitle: 'Foleni iko tupu',
  eventDecision: 'Rejeleo la uamuzi', eventFrom: 'Kutoka', eventHistory: 'Historia ya ukaguzi', eventReviewer: 'Mkaguzi', eventTo: 'Kwenda',
  eventTypes: { claimed: 'Yamechukuliwa', created: 'Mapitio yameundwa', decision_saved: 'Uamuzi umehifadhiwa', released: 'Yamerudishwa kwenye foleni', status_changed: 'Hali imebadilika' },
  evidence: 'Marejeleo ya ushahidi', filterAnswerLanguage: 'Lugha', filterChannel: 'Kituo', filterReviewer: 'Mkaguzi aliyepangiwa',
  filterStatus: 'Hali', filters: 'Vichujio vya foleni', grounded: 'Yana ushahidi', internalNotes: 'Maelezo ya ndani',
  languagePlaceholder: 'mf. ar au en-US', loadDetailsError: 'Maelezo ya mapitio hayakuweza kupakiwa.',
  loadListError: 'Foleni ya mapitio haikuweza kupakiwa kutoka kwenye seva.', loadingDetails: 'Inapakia maelezo…', loadingList: 'Inapakia foleni…',
  metadata: 'Data ya jibu na mapitio', model: 'Muundo', needsChanges: 'Omba mabadiliko ya maudhui', no: 'Hapana',
  noDecision: 'Bado hakuna uamuzi wa mwisho uliohifadhiwa.', noEvents: 'Hakuna matukio yaliyohifadhiwa.',
  noEvidence: 'Hakuna marejeleo ya ushahidi yaliyohifadhiwa kwa jibu hili.', notAvailable: 'Haipatikani', notesOptional: 'Si lazima kwa uamuzi huu',
  notesRequired: 'Yanahitajika kueleza mabadiliko', outcomes: { approved: 'Yameidhinishwa', needs_changes: 'Maudhui yanahitaji mabadiliko', rejected: 'Yamekataliwa' },
  previousPage: 'Ukurasa uliotangulia', nextPage: 'Ukurasa unaofuata', provider: 'Mtoa huduma', question: 'Swali',
  queueLabel: 'Foleni ya mapitio ya walimu', refresh: 'Onyesha upya', reject: 'Kataa', release: 'Rudisha kwenye foleni',
  reviewerFilterPlaceholder: 'Kitambulisho kamili',
  retry: 'Jaribu tena', status: 'Hali ya mapitio',
  statuses: { approved: 'Yameidhinishwa', in_review: 'Yanapitiwa', needs_changes: 'Yanahitaji mabadiliko', pending: 'Yanasubiri', rejected: 'Yamekataliwa' },
  submitDecision: 'Thibitisha na uhifadhi', submitting: 'Inahifadhi…', successClaim: 'Mapitio yamechukuliwa na foleni imesawazishwa.',
  successDecision: 'Uamuzi wa mwisho umehifadhiwa na data imesawazishwa.', successRelease: 'Mapitio yamerudishwa na foleni imesawazishwa.',
  sufficiencies: { insufficient: 'Hautoshi', sufficient: 'Unatosha', unknown: 'Haijulikani' }, sufficiency: 'Utoshelevu wa ushahidi',
  unassigned: 'Hayajapangiwa', updatedAt: 'Yalisasishwa',
  validation: {
    correction_required: 'Ingiza jibu lililosahihishwa kabla ya kuidhinisha.', correction_too_long: 'Jibu lililosahihishwa ni refu kuliko kiwango.',
    notes_required: 'Eleza wazi kinachopaswa kubadilishwa katika maudhui.', notes_too_long: 'Maelezo ya ndani ni marefu kuliko kiwango.',
    request_too_large: 'Maandishi ya uamuzi ni makubwa kuliko kiwango cha seva.',
  },
  viewDetails: (question) => `Tazama maelezo ya mapitio: ${question}`,
  rangeLabel: (start, end, total) => `${start}–${end} kati ya ${total}`,
  reviewCount: (count) => `Mapitio ${count}`, yes: 'Ndiyo', unknown: 'Haijulikani',
};
