import type {
  ReviewDecisionOutcome,
  ReviewEventType,
  ReviewStatus,
} from '../../../../../shared/contracts/reviews';
import type { EvidenceSufficiency } from '../../../../../shared/contracts/question-log';
import type { DecisionMode } from '../types';
import type { ReviewActionValidationCode } from '../review-actions';

export interface ReviewsCopy {
  actionConflict: string;
  actionError: string;
  actionUnavailable: string;
  all: string;
  applyFilters: string;
  answer: string;
  answerLanguage: string;
  approveAsIs: string;
  approveEdited: string;
  assignedReviewer: string;
  cancel: string;
  channel: string;
  chooseReviewBody: string;
  chooseReviewTitle: string;
  claim: string;
  clearFilters: string;
  closeDetails: string;
  confirmDecision: string;
  correctedAnswer: string;
  createdAt: string;
  decidedAt: string;
  decision: string;
  decisionDescriptions: Record<DecisionMode, string>;
  decisionTitles: Record<DecisionMode, string>;
  details: string;
  emptyBody: string;
  emptyTitle: string;
  eventDecision: string;
  eventFrom: string;
  eventHistory: string;
  eventReviewer: string;
  eventTo: string;
  eventTypes: Record<ReviewEventType, string>;
  evidence: string;
  filterAnswerLanguage: string;
  filterChannel: string;
  filterReviewer: string;
  filterStatus: string;
  filters: string;
  grounded: string;
  internalNotes: string;
  languagePlaceholder: string;
  loadDetailsError: string;
  loadListError: string;
  loadingDetails: string;
  loadingList: string;
  metadata: string;
  model: string;
  needsChanges: string;
  no: string;
  noDecision: string;
  noEvents: string;
  noEvidence: string;
  notAvailable: string;
  notesOptional: string;
  notesRequired: string;
  outcomes: Record<ReviewDecisionOutcome, string>;
  previousPage: string;
  nextPage: string;
  provider: string;
  question: string;
  queueLabel: string;
  refresh: string;
  reject: string;
  release: string;
  reviewerFilterPlaceholder: string;
  retry: string;
  status: string;
  statuses: Record<ReviewStatus, string>;
  submitDecision: string;
  submitting: string;
  successClaim: string;
  successDecision: string;
  successRelease: string;
  sufficiencies: Record<EvidenceSufficiency, string>;
  sufficiency: string;
  unassigned: string;
  updatedAt: string;
  validation: Record<ReviewActionValidationCode, string>;
  viewDetails: (question: string) => string;
  rangeLabel: (start: number, end: number, total: number) => string;
  reviewCount: (count: number) => string;
  yes: string;
  unknown: string;
}
