import type { SystemDiagnosticsCopy } from './types';

export const arSystemDiagnosticsCopy: SystemDiagnosticsCopy = {
  botConfigured: 'البوت مُعَدّ',
  botRunning: 'عملية البوت نشطة',
  availableSpace: 'المساحة المتاحة',
  checkedAt: 'آخر فحص',
  checks: {
    'telegram.bot': 'بوت Telegram',
    'storage.data': 'مخزن بيانات التطبيق',
    'storage.documents': 'مخزن المستندات',
    'storage.knowledge': 'مخزن المعرفة',
    'database.books': 'قاعدة بيانات الكتب',
    'database.questions': 'قاعدة بيانات الأسئلة والمراجعات',
    'database.auth': 'قاعدة بيانات تسجيل الدخول',
    'audit.integrity': 'سلامة سجل الأمان',
    'model.configuration': 'إعداد نموذج الإجابة',
    'ocr.tesseract': 'أداة التعرّف الضوئي Tesseract',
    'ocr.pdftoppm': 'أداة تحويل صفحات PDF إلى صور',
  },
  codes: {
    telegram_degraded: 'أبلغ بوت Telegram عن حالة آمنة تحتاج إلى الانتباه.',
    telegram_not_configured: 'بوت Telegram غير مُعَدّ.',
    telegram_running: 'تشغيل بوت Telegram يرسل حالة طبيعية.',
    telegram_status_invalid: 'ملخص حالة Telegram المحلي غير صالح أو غير قابل للقراءة.',
    telegram_status_missing: 'لم ينشر بوت Telegram ملخص حالته المحلية بعد.',
    telegram_status_stale: 'آخر حالة منشورة لبوت Telegram قديمة.',
    access_denied: 'لا يستطيع التطبيق قراءة هذا المورد أو الكتابة فيه.',
    audit_configuration_invalid: 'إعداد سجل الأمان غير مكتمل أو غير صالح.',
    configured: 'النموذج البعيد والبديل المحلي مُعدّان.',
    integrity_invalid: 'فشل التحقق من سلسلة سجل الأمان المحمية.',
    integrity_probe_not_connected: 'فحص سلامة السجل غير متصل بهذه الصفحة بعد.',
    integrity_probe_timeout: 'تجاوز فحص سلامة السجل المهلة الآمنة.',
    integrity_unavailable: 'تعذّر فحص خدمة سجل الأمان المحمية.',
    integrity_unverifiable: 'المفاتيح المتاحة لا تستطيع التحقق من السلسلة كاملة.',
    integrity_valid: 'سلسلة سجل الأمان المحلية الموثّقة سليمة.',
    invalid_database_file: 'الملف المحدد ليس قاعدة بيانات SQLite صالحة.',
    local_only: 'مسار الإجابة المحلي مُعدّ من دون مزود بعيد.',
    not_initialized: 'لم تتم تهيئة هذا المورد بعد.',
    path_probe_timeout: 'تجاوز فحص التخزين المحلي المهلة الآمنة.',
    path_unavailable: 'المورد المحلي المحدد غير متاح.',
    ready: 'المورد قابل للقراءة والكتابة.',
    tool_available: 'الأداة المحلية متاحة.',
    tool_timeout: 'لم تستجب الأداة المحلية خلال المهلة الآمنة.',
    tool_unavailable: 'الأداة المحلية غير متاحة.',
  },
  errorBody: 'تعذّرت قراءة نقطة التشخيص المحمية. قد تكون النتائج السابقة، إن وُجدت، غير محدثة.',
  errorTitle: 'تشخيص النظام غير متاح',
  intro: 'تحقق من مخازن البيانات ومعالجة المستندات وجاهزية النموذج وسلامة سجل الأمان من دون كشف أي أسرار.',
  loading: 'جارٍ تنفيذ فحوص الجاهزية المحلية المحدودة…',
  location: 'الموقع الآمن',
  lastHandledUpdate: 'آخر تحديث تمت معالجته',
  lastSuccessfulPoll: 'آخر استطلاع ناجح',
  modes: {
    local_only: 'محلي فقط',
    remote_with_local_fallback: 'بعيد مع بديل محلي',
    unconfigured: 'غير مُعدّ',
  },
  noDetails: 'لا توجد تفاصيل آمنة إضافية.',
  privacy: 'لا تعرض هذه الصفحة المفاتيح أو مخرجات الأوامر أو أحداث السجل أو المسارات الخارجية الكاملة.',
  publicLink: 'الرابط العام للبوت',
  publicUsername: 'اسم المستخدم العام',
  readable: 'قابل للقراءة',
  refresh: 'إعادة تنفيذ الفحوص',
  refreshing: 'جارٍ الفحص…',
  scopes: { external: 'موقع خارجي مخفي', memory: 'مخزن داخل الذاكرة', workspace: 'مساحة عمل التطبيق' },
  retryCount: 'المحاولات المتتالية',
  runtimeStates: { degraded: 'يحتاج إلى الانتباه', running: 'يعمل' },
  statuses: { healthy: 'سليم', degraded: 'يحتاج انتباهًا', unavailable: 'غير متاح' },
  summary: {
    healthy: 'كل الموارد الأساسية جاهزة والأدوات الاختيارية متاحة.',
    degraded: 'يمكن للتطبيق الاستمرار، لكن توجد إمكانات تحتاج إلى الانتباه.',
    unavailable: 'مورد أساسي غير متاح أو لم يجتز فحص السلامة.',
  },
  title: 'تشخيص النظام',
  telegramErrors: {
    authentication_failed: 'فشل توثيق Telegram.',
    conflict: 'يوجد مستهلك Telegram آخر أو webhook يتعارض مع الاستطلاع.',
    network_unavailable: 'تعذر الوصول إلى Telegram.',
    not_configured: 'إعداد Telegram المطلوب غير موجود.',
    rate_limited: 'قيّد Telegram الطلبات مؤقتًا.',
    request_timeout: 'انتهت مهلة طلب Telegram.',
    service_unavailable: 'خدمة Telegram غير متاحة مؤقتًا.',
    unknown: 'أبلغ البوت عن عطل آمن غير مصنف.',
  },
  versionApi: 'إصدار واجهة API',
  versionApp: 'إصدار التطبيق',
  writable: 'قابل للكتابة',
  yes: 'نعم',
  no: 'لا',
};
