import type { SystemDiagnosticsCopy } from './types';

export const enSystemDiagnosticsCopy: SystemDiagnosticsCopy = {
  availableSpace: 'Available space',
  checkedAt: 'Last checked',
  checks: {
    'storage.data': 'Application data storage',
    'storage.documents': 'Document storage',
    'storage.knowledge': 'Knowledge storage',
    'database.books': 'Books database',
    'database.questions': 'Questions and reviews database',
    'database.auth': 'Authentication database',
    'audit.integrity': 'Security audit integrity',
    'model.configuration': 'Answer model configuration',
    'ocr.tesseract': 'Tesseract OCR',
    'ocr.pdftoppm': 'PDF page rasterizer',
  },
  codes: {
    access_denied: 'The application cannot read or write this resource.',
    audit_configuration_invalid: 'Security-audit configuration is incomplete or invalid.',
    configured: 'Remote answering and a local fallback are configured.',
    integrity_invalid: 'The protected audit chain failed verification.',
    integrity_probe_not_connected: 'Integrity verification is not connected to this diagnostic.',
    integrity_probe_timeout: 'Integrity verification exceeded its safe time limit.',
    integrity_unavailable: 'The protected audit service could not be checked.',
    integrity_unverifiable: 'The available audit keys cannot verify the complete chain.',
    integrity_valid: 'The local authenticated audit chain is valid.',
    invalid_database_file: 'The configured file is not a valid SQLite database.',
    local_only: 'The local answer path is configured without a remote provider.',
    not_initialized: 'This resource has not been initialized yet.',
    path_probe_timeout: 'The local storage check exceeded its safe time limit.',
    path_unavailable: 'The configured local resource is unavailable.',
    ready: 'The resource is readable and writable.',
    tool_available: 'The local tool is available.',
    tool_timeout: 'The local tool did not answer within the safe time limit.',
    tool_unavailable: 'The local tool is not available.',
  },
  errorBody: 'The protected diagnostic endpoint could not be read. Existing results, if any, may be out of date.',
  errorTitle: 'System diagnostics unavailable',
  intro: 'Check local data stores, document processing, model readiness, and protected audit integrity without exposing secrets.',
  loading: 'Running bounded local readiness checks…',
  location: 'Safe location',
  modes: {
    local_only: 'Local only',
    remote_with_local_fallback: 'Remote with local fallback',
    unconfigured: 'Not configured',
  },
  noDetails: 'No additional safe details.',
  privacy: 'This view never displays keys, command output, audit events, or complete external paths.',
  readable: 'Readable',
  refresh: 'Run checks again',
  refreshing: 'Checking…',
  scopes: { external: 'External location (redacted)', memory: 'In-memory storage', workspace: 'Application workspace' },
  statuses: { healthy: 'Healthy', degraded: 'Degraded', unavailable: 'Unavailable' },
  summary: {
    healthy: 'All required resources are ready and optional tools are available.',
    degraded: 'The application can continue, but one or more capabilities need attention.',
    unavailable: 'A required resource is unavailable or failed its safety check.',
  },
  title: 'System diagnostics',
  versionApi: 'API version',
  versionApp: 'Application version',
  writable: 'Writable',
  yes: 'Yes',
  no: 'No',
};
