import type { SystemDiagnosticsCopy } from './types';

export const swSystemDiagnosticsCopy: SystemDiagnosticsCopy = {
  availableSpace: 'Nafasi inayopatikana',
  checkedAt: 'Ukaguzi wa mwisho',
  checks: {
    'storage.data': 'Hifadhi ya data ya programu',
    'storage.documents': 'Hifadhi ya nyaraka',
    'storage.knowledge': 'Hifadhi ya maarifa',
    'database.books': 'Hifadhidata ya vitabu',
    'database.questions': 'Hifadhidata ya maswali na mapitio',
    'database.auth': 'Hifadhidata ya uthibitishaji',
    'audit.integrity': 'Uadilifu wa kumbukumbu ya usalama',
    'model.configuration': 'Mpangilio wa modeli ya majibu',
    'ocr.tesseract': 'Tesseract OCR',
    'ocr.pdftoppm': 'Kigeuzi cha kurasa za PDF',
  },
  codes: {
    access_denied: 'Programu haiwezi kusoma au kuandika rasilimali hii.',
    audit_configuration_invalid: 'Mpangilio wa kumbukumbu ya usalama haujakamilika au si sahihi.',
    configured: 'Modeli ya mbali na mbadala wa ndani zimesanidiwa.',
    integrity_invalid: 'Mlolongo wa kumbukumbu iliyolindwa umeshindwa kuthibitishwa.',
    integrity_probe_not_connected: 'Ukaguzi wa uadilifu haujaunganishwa na uchunguzi huu.',
    integrity_probe_timeout: 'Ukaguzi wa uadilifu umezidi muda salama.',
    integrity_unavailable: 'Huduma ya kumbukumbu iliyolindwa haikuweza kukaguliwa.',
    integrity_unverifiable: 'Funguo zilizopo haziwezi kuthibitisha mlolongo wote.',
    integrity_valid: 'Mlolongo wa kumbukumbu ya ndani uliothibitishwa ni halali.',
    invalid_database_file: 'Faili iliyosanidiwa si hifadhidata halali ya SQLite.',
    local_only: 'Njia ya majibu ya ndani imesanidiwa bila mtoa huduma wa mbali.',
    not_initialized: 'Rasilimali hii bado haijaanzishwa.',
    path_probe_timeout: 'Ukaguzi wa hifadhi ya ndani umezidi muda salama.',
    path_unavailable: 'Rasilimali ya ndani iliyosanidiwa haipatikani.',
    ready: 'Rasilimali inaweza kusomwa na kuandikwa.',
    tool_available: 'Zana ya ndani inapatikana.',
    tool_timeout: 'Zana ya ndani haikujibu ndani ya muda salama.',
    tool_unavailable: 'Zana ya ndani haipatikani.',
  },
  errorBody: 'Sehemu ya uchunguzi iliyolindwa haikuweza kusomwa. Matokeo ya awali yanaweza kuwa ya zamani.',
  errorTitle: 'Uchunguzi wa mfumo haupatikani',
  intro: 'Kagua hifadhi za data, usindikaji wa nyaraka, utayari wa modeli na uadilifu wa kumbukumbu bila kufichua siri.',
  loading: 'Inaendesha ukaguzi salama wa utayari wa ndani…',
  location: 'Mahali salama',
  modes: {
    local_only: 'Ndani pekee',
    remote_with_local_fallback: 'Mbali na mbadala wa ndani',
    unconfigured: 'Haijasanidiwa',
  },
  noDetails: 'Hakuna maelezo mengine salama.',
  privacy: 'Mwonekano huu hauonyeshi funguo, matokeo ya amri, matukio ya kumbukumbu, au njia kamili za nje.',
  readable: 'Inasomeka',
  refresh: 'Endesha ukaguzi tena',
  refreshing: 'Inakagua…',
  scopes: { external: 'Mahali pa nje pamefichwa', memory: 'Hifadhi ya kumbukumbu', workspace: 'Eneo la kazi la programu' },
  statuses: { healthy: 'Salama', degraded: 'Inahitaji uangalizi', unavailable: 'Haipatikani' },
  summary: {
    healthy: 'Rasilimali zote muhimu ziko tayari na zana za hiari zinapatikana.',
    degraded: 'Programu inaweza kuendelea, lakini uwezo fulani unahitaji uangalizi.',
    unavailable: 'Rasilimali muhimu haipatikani au imeshindwa ukaguzi wa usalama.',
  },
  title: 'Uchunguzi wa mfumo',
  versionApi: 'Toleo la API',
  versionApp: 'Toleo la programu',
  writable: 'Inaandikika',
  yes: 'Ndiyo',
  no: 'Hapana',
};
