create table public.knowledge_documents (
  id uuid primary key default gen_random_uuid(),
  title text not null check (char_length(btrim(title)) > 0),
  source_path text,
  is_published boolean not null default false,
  created_at timestamptz not null default now()
);

create table public.knowledge_chunks (
  id bigint generated by default as identity primary key,
  document_id uuid not null references public.knowledge_documents(id) on delete cascade,
  ordinal integer not null check (ordinal >= 0),
  content text not null check (char_length(btrim(content)) > 0),
  search_vector tsvector generated always as (to_tsvector('simple', content)) stored,
  created_at timestamptz not null default now(),
  unique (document_id, ordinal)
);

create index knowledge_chunks_search_vector_idx
  on public.knowledge_chunks
  using gin (search_vector);

create index knowledge_chunks_document_id_idx
  on public.knowledge_chunks (document_id);

alter table public.knowledge_documents enable row level security;
alter table public.knowledge_chunks enable row level security;

revoke all on table public.knowledge_documents from anon, authenticated;
revoke all on table public.knowledge_chunks from anon, authenticated;
revoke all on sequence public.knowledge_chunks_id_seq from anon, authenticated;

grant select, insert, update, delete on table public.knowledge_documents to service_role;
grant select, insert, update, delete on table public.knowledge_chunks to service_role;
grant usage, select on sequence public.knowledge_chunks_id_seq to service_role;

create function public.search_published_knowledge(
  search_text text,
  match_count integer default 6
)
returns table (
  chunk_id bigint,
  content text,
  rank real
)
language sql
stable
security invoker
set search_path = ''
as $$
  with search_query as (
    select websearch_to_tsquery('simple', search_text) as query
  )
  select
    chunk.id as chunk_id,
    chunk.content,
    ts_rank_cd(chunk.search_vector, search_query.query) as rank
  from public.knowledge_chunks as chunk
  join public.knowledge_documents as document
    on document.id = chunk.document_id
  cross join search_query
  where document.is_published
    and chunk.search_vector @@ search_query.query
  order by rank desc, chunk.id
  limit least(greatest(match_count, 1), 12);
$$;

revoke all on function public.search_published_knowledge(text, integer) from public, anon, authenticated;
grant execute on function public.search_published_knowledge(text, integer) to service_role;

comment on function public.search_published_knowledge(text, integer) is
  'Returns ranked excerpts from published learning documents for server-side grounded answers.';
